### ISSUE TITLE
Doesn't seem to work for the latest version of VS Code

### ISSUE THREAD

**Issue by istudiomobile** [ionutvmi/path-autocomplete#11] opened 2017-04-25 12:20 UTC
Installed but nothing happens as start to write path. Latest version of VS Code.

**Comment by ionutvmi** [comment] 2017-04-25 17:55
Can you please provide more information about your environment ?
vscode version, OS

Please keep in mind that the autocomplete only works inside quotes.
Example: `<a href="./data/"`

**Comment by ionutvmi** [comment] 2017-05-19 16:37
closing this as no feedback was received.

**Comment by alexpusch** [comment] 2017-06-03 13:39
Doesn't work for me to. Simple require('./...') doesn't give any suggestions

 VS code version 1.12.2, Ubuntu 17.04

**Closed** 2017-06-04 23:02 UTC

**Comment by ionutvmi** [comment] 2017-06-04 23:07
I got an ubuntu VM and I was able to reproduce the issue.
It was caused by a file that got the wrong name during the publish process.
The issue should be fixed in 1.5.1

Please let me know if you still have issues.

**Comment by fbaiodias** [comment] 2017-06-13 13:14
Hey @ionutvmi! Local path completion isn't working for me on OSX 10.12.5, VS Code 1.13.0, Path Autocomplete 1.5.1. `node_modules` completion seems to work fine though.
