### ISSUE TITLE
Support aliases

### ISSUE THREAD

**Issue by janhancic** [ionutvmi/path-autocomplete#10] opened 2017-04-18 14:30 UTC
In our JS app we use bael and it's aliases feature, so we can do stuff like `import Foo from '@common/js/var/Foo`. On disk `Foo` is in `workspace_dir/commonjs/var/Foo` as you would expect, the reason we use `@common` is so you don't end up with insane relative paths when importing stuff from common when you are somewhere deep in the project.

Would it be possible to support these sort of aliases in the extension?

**Comment by ionutvmi** [comment] 2017-04-22 07:14
Have you tired using the `path-autocomplete.pathMappings` option ?
It should do exactly that.

**Comment by ionutvmi** [comment] 2017-04-22 08:37
I'm closing this issue at the moment. Fell free to open it if you have any issues with those pathMapprings.

**Closed by ionutvmi** 2017-04-22 08:37 UTC

**Comment by janhancic** [comment] 2017-04-24 09:15
I tried that, but it either doesn't work or (more likely) I don't understand how it's supposed to work.

I tried configuring:

```
"path-autocomplete.pathMappings": {
   "@": "${workspace}"
   // or
   "@common": "${workspace}/common"
 }
```

With both I don't get any autocompletion when I start typing `import ... from '@common';`.

What am I doing wrong?

**Comment by ionutvmi** [comment] 2017-04-25 17:52
```
   "@common": "${workspace}/common"
```
I just tried it locally and it works as expected. 
If I type "@common/" i get the autocomplete list.

Did you try to restart vscode after changing the configurations ?

**Comment by janhancic** [comment] 2017-04-26 09:16
After restarting vscode I do get auto completion (it would be nice if this wasn't required) after I type `@common/`. But only for that level. If I then continue typing a folder (`@common/js/`) then completions stop.

**Comment by janhancic** [comment] 2017-05-30 10:10
Any new info on this?

**Comment by ionutvmi** [comment] 2017-05-30 17:42
Ho @janhancic ,

I was not able to reproduce the issue. Maybe you can provide an example folder structure that doesn't work for you ?

**Comment by janhancic** [comment] 2017-05-31 09:10
```
common/
  bash/
  js/
    components/
    utils/
      date/
    ...
  ...
app/
  index.js
```

In `index.js` I would type `import foo from '@common/...` at which point I would get a list of `bash`, `js` & other folders in `common`. After `import foo from '@common/js/...` I don't get any suggestions any more.

My settings look like this:

```
"path-autocomplete.pathMappings": {
    "@common/": "${workspace}/common"
  }
```

Any other info I can give?

**Comment by ionutvmi** [comment] 2017-05-31 09:59
the mapping seems to have an additional `/`
Can you try with something like:

```
"path-autocomplete.pathMappings": {
    "@common": "${workspace}/common"
  }
```

**Comment by janhancic** [comment] 2017-05-31 10:02
Amazing, that seems to have fixed it! Thank you very much!
