### ISSUE TITLE
Keyboard navigation stopped working recently

### ISSUE THREAD

**Issue by anishmittal2020** [ionutvmi/path-autocomplete#59] opened 2018-12-18 23:51 UTC
Example: I want to type path `./Sync/Hello.pdf`. 

**Previously**, I could select Sync from drop down menu by navigating to it and pressing enter and then  it used to show me all files inside Sync folder in a drop down menu, from which Hello.pdf could be selected by pressing enter (I didn't need to use mouse at all).

**Now**, if I press enter as above nothing gets printed and the drop down list goes away. It works only if I use mouse to click (instead of enter).

Please resolve this issue.

**Comment by ionutvmi** [comment] 2019-03-23 19:24
Hi @anishmittal2020 ,

I am not able to reproduce this issue.
Is this issue still valid with the most recent version of vscode and the extension ?

**Comment by ionutvmi** [comment] 2019-04-28 13:24
Closing this for now.
Please reopen this if you still encounter issues.

**Closed** 2019-04-28 13:24 UTC
